### PR TITLE
Terraform v0.12

### LINKED ISSUE #10: Add support for Terraform v0.12

### PR DESCRIPTION
**Pull request by aaron-lane**
This branch fixes #10.

### CODE REVIEW

**Comment by tdigangi** [comment]
@ingwarr the primary module([terraform-google-bigquery/main.tf](https://github.com/terraform-google-modules/terraform-google-bigquery/blob/aaron-lane-0.12/main.tf), etc) does not appear to have been converted to v0.12 syntax and there is no upgrade guide for 2.0.0. Are these items a WIP?

**Comment by ingwarr** [comment]
@tdigangi Oops, my bad, I forgot about it, I'll fix it in the nearest time

**Comment by tdigangi** [comment]
I have ran through the upgrade with v0.12.2 the examples, module, and tests appear to function properly. 

The only things that are outstanding for the merge are the upgrade guide(which should be minimal) and ensure this includes the `bundle install` in the root module. Tests will fail without the latest gems. @ingwarr do you have the bandwidth to handle these items?

**Comment by tdigangi** [comment]
@aaron-lane Can we merge this branch in I have created [Issue 24](https://github.com/terraform-google-modules/terraform-google-bigquery/issues/24) in which we will add an upgrade guide.

**Pull request merged**
