### PR TITLE
Initial addition of UDF module

### PR DESCRIPTION
**Pull request by milesmatthias**

### CODE REVIEW

**Comment by milesmatthias** [comment]
@morgante is this what you were thinking for this module? Or were you thinking of supporting custom UDFs?

**Comment by morgante** [comment]
@milesmatthias Yup! The only ask I'd have is whether we could update this to use the `gcloud` module to run commands.

**Comment by milesmatthias** [comment]
@morgante the only potential issue there is that one of the UDFs depends on another one, so I added a couple outputs to the gcloud module, and am trying to get the modules to depend on each other.

**Comment by milesmatthias** [comment]
I've verified that the tests pass locally for this module...

**Comment by milesmatthias** [comment]
Linting will be fixed by https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/523.

**Comment by milesmatthias** [comment]
One of the functions this module adds to a BigQuery table depends on a different function it's adding, but using the output of the module isn't forcing TF to wait until it's defined:

```
       Error: Error running command 'PATH=/workspace/test/fixtures/full/.terraform/modules/example.bigquery.udfs.bq_parse_url/cache/linux/google-cloud-sdk/bin:$PATH
       bq --project_id ci-bigquery-cdb1 query --use_legacy_sql=false "CREATE FUNCTION IF NOT EXISTS foo.parse_url(url STRING, part STRING)
         AS (
           CASE
             -- Return HOST part of the URL.
             WHEN part = 'HOST' THEN SPLIT(\`ci-bigquery-cdb1\`.foo.check_protocol(url), '/')[OFFSET(2)]
             WHEN part = 'REF' THEN
        IF(REGEXP_CONTAINS(url, '#'), SPLIT(\`ci-bigquery-cdb1\`.foo.check_protocol
        (url), '#')[OFFSET(1)], NULL)
             WHEN part = 'PROTOCOL' THEN RTRIM(REGEXP_EXTRACT(url, '^[a-zA-Z]+://'), '://')
             ELSE ''
           END
         );"
       
       ': exit status 1. Output: 
       Error in query string: Error processing job 'ci-bigquery-
       cdb1:bqjob_r218dae87492b73e1_0000016f300aa4ae_1': Function not found: `ci-
       bigquery-cdb1`.foo.check_protocol at [5:37]
```

Might need to experiment with some `sleep`s

**Comment by milesmatthias** [comment]
@morgante would love any thoughts you have here to help unblock me. Thanks!

**Comment by morgante** [comment]
@milesmatthias Try printing the dependency graph to make sure the second null_resource is actually dependent on the first null_resource. We might need to tweak the `gcloud` module output dependencies.

**Comment by milesmatthias** [comment]
Yup, it wasn't actually depending on it, so I had to add this output: https://github.com/terraform-google-modules/terraform-google-gcloud/pull/13

**Comment by morgante** [comment]
@milesmatthias Could you rebase?

**Comment by milesmatthias** [comment]
@morgante all the tests are green now.

**Pull request merged**
