### PR TITLE
feat: add support for `require_partition_filter` in the external tables

### PR DESCRIPTION
**Pull request by NitriKx**
This PR adds the `require_partition_filter` option for the external tables. 

From what I've experimented it seems that the "top-level" `require_partition_filter` option does not work here and needs to be set in the `hive_partitioning_options`.

### CODE REVIEW

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @NitriKx! Could you regenerate the docs running `make docker_generate_docs`?

**Comment by NitriKx** [comment]
Oops forgot this step, I've just pushed the doc update @bharathkkb

**Comment by NitriKx** [comment]
Hello @bharathkkb, any news on this one?

**Pull request closed without merging**
