### PR TITLE
feat!: switch schema from filepath to json string

### LINKED ISSUE #91: Support using schema JSON string directly instead of a schema file
Hi there!

In the Terraform `google_bigquery_table` ressource, [`schema` expects a JSON string](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#schema), however this module forces `schema` to be a file path because `file()` is used:

https://github.com/terraform-google-modules/terraform-google-bigquery/blob/ebe17b80b2fefc692787e6ef5f232ae6804ad9d2/main.tf#L60

I think this takes away some of the original flexibility of `google_bigquery_table`. I prefer using this well designed module over doing everything BQ separately, however in my current case I already had all the schemas in a map.

Just a nice to have! 👍

### PR DESCRIPTION
**Pull request by bharathkkb**
fixes #91

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — APPROVED** [review]
This will need to be a break change.

**Comment by bharathkkb** [comment]
@morgante ack, next release is breaking

**Comment by kunalkg11** [comment]
LGTM

**Review by kunalkg11 — COMMENTED** [review]
LGTM

**Review by kunalkg11 — APPROVED** [review]

**Pull request merged**
